# iris資料集介紹：

In [1]:
#這行是在ipython notebook的介面裏專用，如果在其他介面則可以拿掉
%matplotlib inline

import matplotlib.pyplot as plt
#from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
#from sklearn.decomposition import PCA

# import some data to play with
iris = datasets.load_iris()


In [2]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
print(iris['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
print(iris['data'])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print(iris['target'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [8]:
import pandas as pd

In [9]:
x=pd.DataFrame(iris['data'], columns=iris['feature_names'])
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [10]:
y=pd.DataFrame(iris['target'], columns=['target_names'])
y

target_names
0               0
1               0
2               0
3               0
4               0
..            ...
145             2
146             2
147             2
148             2
149             2

[150 rows x 1 columns]

In [11]:
data=pd.concat([x,y],axis=1)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target_names  
0               0  
1               0  
2               0  
3               0  
4               0  
..            ...  
145             2  
146             2  
147             2  
148             2  
149             2  

[150 rows x 5 columns]

# 資料預處理(data preprocessing)

In [12]:
x, y =iris.data, iris.target

In [13]:
from sklearn.preprocessing import OneHotEncoder
from keras.utils import np_utils
y_OneHot = np_utils.to_categorical(y)

Using TensorFlow backend.


In [14]:
import numpy as np
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
x, y_OneHot, test_size=0.2, random_state=42)

In [15]:
x_train.shape

(120, 4)

# 建立模型

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
model = Sequential()

In [17]:
#將「輸入層」與「隱藏層」加入模型
model.add(Dense(units=100, #神經元
                input_dim=4, #輸入資料
                kernel_initializer='normal', 
                activation='relu'))

In [18]:
model.add(Dropout(0.15))#每經過一層神經元，就把一部分(15%)的內容抽掉


Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [19]:
model.add(Dense(units=3, 
                kernel_initializer='normal', 
                activation='softmax'))

In [20]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 100)               500       
_________________________________________________________________
dropout_1 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 303       
Total params: 803
Trainable params: 803
Non-trainable params: 0
_________________________________________________________________
None


# 訓練模型

In [21]:
model.compile(loss='categorical_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [23]:
train_history=model.fit(x=x_train,
                        y=y_train,validation_split=0.2, 
                        epochs=10, batch_size=12,verbose=2)  
#重要!!validation_split將訓練資料的0.2取出作為驗證資料
#epochs訓練週期 batch_size每個週期抽200筆去訓練，
#共(96/12)8批 verbose=2顯示訓練過程

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 96 samples, validate on 24 samples
Epoch 1/10





 - 0s - loss: 1.1049 - acc: 0.4062 - val_loss: 1.0716 - val_acc: 0.7083
Epoch 2/10
 - 0s - loss: 1.0615 - acc: 0.6250 - val_loss: 1.0467 - val_acc: 0.7917
Epoch 3/10
 - 0s - loss: 1.0278 - acc: 0.7188 - val_loss: 1.0133 - val_acc: 0.5000
Epoch 4/10
 - 0s - loss: 0.9929 - acc: 0.7292 - val_loss: 0.9810 - val_acc: 0.5000
Epoch 5/10
 - 0s - loss: 0.9637 - acc: 0.7188 - val_loss: 0.9499 - val_acc: 0.5833
Epoch 6/10
 - 0s - loss: 0.9069 - acc: 0.8333 - val_loss: 0.9162 - val_acc: 0.5000
Epoch 7/10
 - 0s - loss: 0.8799 - acc: 0.7604 - val_loss: 0.8750 - val_acc: 0.7500
Epoch 8/10
 - 0s - loss: 0.8397 - acc: 0.7604 - val_loss: 0.8304 - val_acc: 0.9583
Epoch 9/10
 - 0s - loss: 0.7879 - acc: 0.8229 - val_loss: 0.8042 - val_acc: 0.9583
Epoch 10/10
 - 0s - loss: 0.7468 - acc: 0.8229 - val_loss: 0.7560 - val_acc: 1.0000
